<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-item_Sold  Disposed</name>
   <tag></tag>
   <elementGuidId>e5099147-4e47-4385-994c-5b5b79a847b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-item-36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[@id='tab-item-36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-tab-item</value>
      <webElementGuid>9a2053ca-93dd-447e-9ab4-babeeb160f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>36f69036-6668-4661-93bd-0055dab60187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-tab </value>
      <webElementGuid>6fedf5d7-9710-4487-9d6f-75c0ba12f76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>tab in $mdTabsCtrl.tabs</value>
      <webElementGuid>1d5ca8b6-4eca-490e-99af-925be9cdb190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7ea3245d-41d5-4640-bf0f-a48cfb65bba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-item-36</value>
      <webElementGuid>266e1b54-04d0-4c17-bcc5-eae70634d7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tab-id</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>341fd85b-451a-4d50-851f-724c54f4d85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af582b42-c21e-4b0e-be80-43a9b4dde545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39d74986-d46a-427c-8182-08d2f711c289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$mdTabsCtrl.select(tab.getIndex())</value>
      <webElementGuid>b2cab48c-a85f-46fe-8fc6-9c9102e5f729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = true</value>
      <webElementGuid>1b1a318f-2e22-435f-942d-4204ac25b8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = false</value>
      <webElementGuid>f39c91bd-a80d-4f55-9527-615bcedb3f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-active':    tab.isActive(), 'md-focused':   tab.hasFocus(), 'md-disabled':  tab.scope.disabled }</value>
      <webElementGuid>cf98a7aa-7ad8-4b76-962d-cccebfffab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>tab.scope.disabled</value>
      <webElementGuid>f6e147fa-1d22-4c36-a4e6-5d8c7767fdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-left</name>
      <type>Main</type>
      <value>$mdTabsCtrl.nextPage()</value>
      <webElementGuid>11713f95-a16d-40c5-aff6-c79ef399266a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-right</name>
      <type>Main</type>
      <value>$mdTabsCtrl.previousPage()</value>
      <webElementGuid>4cb11f9b-4ff8-4104-87b6-58462e7bbde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tabs-template</name>
      <type>Main</type>
      <value>::tab.label</value>
      <webElementGuid>79bcbfdb-0c38-49fe-9129-35a2dbfac170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-scope</name>
      <type>Main</type>
      <value>::tab.parent</value>
      <webElementGuid>00831876-d2a0-49ac-9b49-f76094a4a7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-content-36</value>
      <webElementGuid>6f016f0d-69a2-4dd6-bfb2-922e5d589746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sold &amp; Disposed
                
            </value>
      <webElementGuid>57ba7fd2-b285-4ba4-ac9b-611f406cdcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-item-36&quot;)</value>
      <webElementGuid>e648dcbf-a0d1-4e6d-8d09-e2f5ba75b7d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id='tab-item-36']</value>
      <webElementGuid>f0ecf597-1ec8-4f9c-a050-fa20909bc307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/md-tabs/md-tabs-wrapper/md-tabs-canvas/md-pagination-wrapper/md-tab-item[3]</value>
      <webElementGuid>07dae327-62b0-4f71-aca6-e2c94bf5fc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered'])[1]/following::md-tab-item[1]</value>
      <webElementGuid>153a11d5-2bfb-433e-b110-80a4876e1876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2)'])[1]/following::md-tab-item[2]</value>
      <webElementGuid>81446cc7-a7bd-4ed2-b9b3-51866c93a840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2)'])[2]/preceding::md-tab-item[1]</value>
      <webElementGuid>667ff11e-6c00-4489-9c5d-28b349336ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sold &amp; Disposed']/parent::*</value>
      <webElementGuid>4b952d54-a157-4f00-980a-1c41d59e00b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-tab-item[3]</value>
      <webElementGuid>408d4a7d-3870-49f6-94d9-5e02e01dbf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id = 'tab-item-36' and (text() = '
                Sold &amp; Disposed
                
            ' or . = '
                Sold &amp; Disposed
                
            ')]</value>
      <webElementGuid>54d76a2d-6577-4f14-9ee8-a2e11f787102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
