<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-item_Outgoing</name>
   <tag></tag>
   <elementGuidId>2210c768-13c3-4771-89a3-43984d3e6469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-item-48</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[@id='tab-item-48']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-tab-item</value>
      <webElementGuid>59506601-450d-4e0d-9d9b-c409c692d9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2ed08b40-adcc-4ba0-8cf6-7f6d1b9b985b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-tab </value>
      <webElementGuid>07958ef5-414f-4098-b2d1-862b04ef1abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>tab in $mdTabsCtrl.tabs</value>
      <webElementGuid>065dd758-71a2-47b2-b60d-5e47523b8abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4f251f67-9d4a-4bac-a413-acf7b72eba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-item-48</value>
      <webElementGuid>54e92548-a713-4b53-a315-94e982d73c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tab-id</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>a6b31c35-3f6d-4a73-a301-99dcfa71bc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>798a5259-bb92-4666-aba4-e03d511b2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4372fe18-66ff-4884-8542-12f4b5c8af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$mdTabsCtrl.select(tab.getIndex())</value>
      <webElementGuid>ff7d07e6-3fe7-4fa2-813d-a12c0d46c4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = true</value>
      <webElementGuid>b6f1faaf-33c2-496e-91d9-f75353b393b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = false</value>
      <webElementGuid>8862a729-8f87-4acb-bd84-a479d7af4e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-active':    tab.isActive(), 'md-focused':   tab.hasFocus(), 'md-disabled':  tab.scope.disabled }</value>
      <webElementGuid>6831df03-19e0-4705-8192-cc25289b11b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>tab.scope.disabled</value>
      <webElementGuid>0e0ebb13-18fd-4a31-9397-58599cd80e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-left</name>
      <type>Main</type>
      <value>$mdTabsCtrl.nextPage()</value>
      <webElementGuid>282eaa1e-5fef-41c7-9fac-1d1b97bc288c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-right</name>
      <type>Main</type>
      <value>$mdTabsCtrl.previousPage()</value>
      <webElementGuid>2e25a787-c63d-4310-93a5-c86955c9e91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tabs-template</name>
      <type>Main</type>
      <value>::tab.label</value>
      <webElementGuid>83860f27-4a8d-42c3-84ef-dc493dbf443c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-scope</name>
      <type>Main</type>
      <value>::tab.parent</value>
      <webElementGuid>852832f5-2ab7-40b2-8984-90cdcb0f32e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-content-48</value>
      <webElementGuid>a1c4c2c3-a5b3-4d17-a687-fc69fcb47c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outgoing</value>
      <webElementGuid>6e8d5c4d-3f81-4dae-acf0-b3391ce889fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-item-48&quot;)</value>
      <webElementGuid>77cd755b-1cdc-4ac3-a3c5-2df47f29fc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id='tab-item-48']</value>
      <webElementGuid>c3623edc-657c-4aa0-b296-9f8734aad894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/md-tabs/md-tabs-wrapper/md-tabs-canvas/md-pagination-wrapper/md-tab-item[2]</value>
      <webElementGuid>832ee593-f20a-4474-8955-86186ec7b3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming'])[2]/following::md-tab-item[1]</value>
      <webElementGuid>d3581f0b-9a4e-4aa4-8afd-b27bef94d9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reversal Pickings'])[3]/following::md-tab-item[2]</value>
      <webElementGuid>b285d2db-bb80-4f57-9e8a-480bdbfb2e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming'])[3]/preceding::md-tab-item[1]</value>
      <webElementGuid>c8ca2505-6851-4154-bdec-9c41a32bc5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outgoing'])[3]/preceding::md-tab-item[1]</value>
      <webElementGuid>02d97104-9c10-4894-953f-fb725bd4343c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-tab-item[2]</value>
      <webElementGuid>afb1d4f4-ad02-40b8-8e9d-effddd6a5d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id = 'tab-item-48' and (text() = 'Outgoing' or . = 'Outgoing')]</value>
      <webElementGuid>63e6d091-bc1c-4ccf-89b8-ce68f72a6872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
