<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-item_All</name>
   <tag></tag>
   <elementGuidId>ce97eebc-55cf-4700-9bd7-c7dbeab1e207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-item-47</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[@id='tab-item-47']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-tab-item</value>
      <webElementGuid>601694ce-ace9-4061-9380-a65ec096f094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82e44c07-32a1-467a-af12-f5285fcc54a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-tab  md-active</value>
      <webElementGuid>40ae069f-99e1-465d-913a-0dbea79a585d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>tab in $mdTabsCtrl.tabs</value>
      <webElementGuid>70a7c023-a087-4f6e-a7ae-24e3dea335ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>219647db-60d9-4c1d-8c7f-f05c59a19969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-item-47</value>
      <webElementGuid>22662e4f-9ee0-459c-b5cd-93784d1fdcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tab-id</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>1ba6e280-1146-49aa-97d1-68a41f6af375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f28db54b-91b4-437d-b2d1-6c0c5aa508aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4149685-b0eb-41c7-a316-a399158883f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$mdTabsCtrl.select(tab.getIndex())</value>
      <webElementGuid>1357b825-7b96-4dd0-b8ef-049bb9808756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = true</value>
      <webElementGuid>9db206d4-2c88-46c8-99b7-4169ddd37f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = false</value>
      <webElementGuid>2af43608-9af3-4840-81c4-e8323b6e8aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-active':    tab.isActive(), 'md-focused':   tab.hasFocus(), 'md-disabled':  tab.scope.disabled }</value>
      <webElementGuid>b348bdb8-a7d4-40be-aaf7-ff137fbe901c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>tab.scope.disabled</value>
      <webElementGuid>e258af20-e248-4783-a4b8-e67a5702aae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-left</name>
      <type>Main</type>
      <value>$mdTabsCtrl.nextPage()</value>
      <webElementGuid>9242abb5-ecb4-411d-a25b-e9c59e171fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-right</name>
      <type>Main</type>
      <value>$mdTabsCtrl.previousPage()</value>
      <webElementGuid>2b3cec77-a3f0-47cb-b60e-47a70fc7a5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tabs-template</name>
      <type>Main</type>
      <value>::tab.label</value>
      <webElementGuid>3875372f-59b0-4f05-87d7-694106250b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-scope</name>
      <type>Main</type>
      <value>::tab.parent</value>
      <webElementGuid>7dbe9704-d826-40c1-a664-a0201895df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-content-47</value>
      <webElementGuid>3b1a11b5-27d0-46d1-9307-660312032045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>b4c9dd80-a0a7-4eba-a09f-a64f3c2a7d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-item-47&quot;)</value>
      <webElementGuid>3d4e61ed-10d9-49b2-b49b-89bf07671ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id='tab-item-47']</value>
      <webElementGuid>771b281d-610a-43ce-acc7-bbe8a9d67cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/md-tabs/md-tabs-wrapper/md-tabs-canvas/md-pagination-wrapper/md-tab-item</value>
      <webElementGuid>68b7dd70-bb7c-4b82-aff1-3a563a622710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Adjustment'])[1]/following::md-tab-item[1]</value>
      <webElementGuid>8bb89c87-3e87-498a-9444-0b266b2f6437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Upload'])[1]/following::md-tab-item[1]</value>
      <webElementGuid>d204669f-89bb-451b-82fa-0e49b90de9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::md-tab-item[1]</value>
      <webElementGuid>cb38dc3d-630c-4c36-a115-1042e8350864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Process'])[1]/preceding::md-tab-item[2]</value>
      <webElementGuid>4b539a51-d32b-4a2d-a3e7-3498e0f1106e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>8e9b303a-8849-4f82-b046-a500ae686d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-tab-item</value>
      <webElementGuid>292c1a4a-6d5d-4d49-a282-4ea78dbcb1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id = 'tab-item-47' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>fee14ad1-83ed-456a-866d-e28b2d94eaf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
