<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-item_Waiting Approval</name>
   <tag></tag>
   <elementGuidId>5d64fa40-8db2-4330-9b70-87a7540e1f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-item-158</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[@id='tab-item-158']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-tab-item</value>
      <webElementGuid>f6feb8d1-2ae4-48f6-afd9-d845ceffdc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f8dd24f5-673b-4194-a2b9-43b0f20dbd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-tab </value>
      <webElementGuid>ab2a1d1d-d23e-43dd-91a8-c68c078220f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>tab in $mdTabsCtrl.tabs</value>
      <webElementGuid>d8ad744c-4ca2-4e6e-88c3-a8c551757eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0951e408-092e-40d4-a205-d4849f8562ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-item-158</value>
      <webElementGuid>01eb5fd0-250b-4fbe-bd7c-c245a7dae941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tab-id</name>
      <type>Main</type>
      <value>158</value>
      <webElementGuid>f80ee2de-b6b4-4886-8d0b-6a49dbcd2cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fc5dab5-aa52-4b70-ad56-747f9035dd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b831f3b5-19fe-42aa-8c14-5b7a37fa91e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$mdTabsCtrl.select(tab.getIndex())</value>
      <webElementGuid>6803560e-1408-4a1d-a022-e43d493f27ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = true</value>
      <webElementGuid>ed32045f-71d4-4814-9583-68cddb529025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = false</value>
      <webElementGuid>b318000c-a791-474b-8409-c6b55b8cff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-active':    tab.isActive(), 'md-focused':   tab.hasFocus(), 'md-disabled':  tab.scope.disabled }</value>
      <webElementGuid>a13f53ff-f565-48a9-b323-b192c3853de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>tab.scope.disabled</value>
      <webElementGuid>a04ff7f5-7743-48dc-8541-a6c6529e7342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-left</name>
      <type>Main</type>
      <value>$mdTabsCtrl.nextPage()</value>
      <webElementGuid>dc518cc8-6e9c-4429-81e5-8dc7fb273a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-right</name>
      <type>Main</type>
      <value>$mdTabsCtrl.previousPage()</value>
      <webElementGuid>662ff761-0756-4789-8a08-f1cb65ec943c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tabs-template</name>
      <type>Main</type>
      <value>::tab.label</value>
      <webElementGuid>4a488dfa-fceb-45fd-b862-9b6b98e67c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-scope</name>
      <type>Main</type>
      <value>::tab.parent</value>
      <webElementGuid>d5647d1f-368c-4da5-a62c-d6d58a337b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-content-158</value>
      <webElementGuid>53693500-0f7f-4a95-b746-524d1c749328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Waiting Approval</value>
      <webElementGuid>5763dc9d-8bf8-40f3-9b7a-1ca7cc48ad99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-item-158&quot;)</value>
      <webElementGuid>35ed880d-f35c-493e-9c4f-ff2dbd57b96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id='tab-item-158']</value>
      <webElementGuid>41389f30-763f-49f3-8c62-f12bf4a20238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/md-tabs/md-tabs-wrapper/md-tabs-canvas/md-pagination-wrapper/md-tab-item[4]</value>
      <webElementGuid>db0240f4-86c7-4731-bc2c-6676da2933f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferring'])[1]/following::md-tab-item[1]</value>
      <webElementGuid>3002d4be-2a6e-43f9-a8df-899987954708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::md-tab-item[2]</value>
      <webElementGuid>5fa7d0cc-efe0-4d14-b03c-e2717b142840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::md-tab-item[1]</value>
      <webElementGuid>74628849-a7f1-44ec-a479-4f5873964731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled'])[1]/preceding::md-tab-item[2]</value>
      <webElementGuid>48e7c772-b309-478e-8557-092c52d668c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waiting Approval']/parent::*</value>
      <webElementGuid>e38d305e-6f45-4b0f-8f3b-f25f7ec4c66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-tab-item[4]</value>
      <webElementGuid>5075e23e-0724-4705-a336-d630477c9092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id = 'tab-item-158' and (text() = 'Waiting Approval' or . = 'Waiting Approval')]</value>
      <webElementGuid>81d2549d-861c-4d53-9c03-ca55a294fb3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
