<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-tab-item_Incoming</name>
   <tag></tag>
   <elementGuidId>a9b6b82a-f6db-485c-a2c7-d319c3d08ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-item-47</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-item[@id='tab-item-47']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-tab-item</value>
      <webElementGuid>aed14d89-ad70-44e4-bf1f-3271d986053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>15fe7079-ce01-4a74-a127-d4b76ccf313f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-tab  md-active</value>
      <webElementGuid>8ef54604-45ec-4b5f-a8ea-1ee0c1769625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>tab in $mdTabsCtrl.tabs</value>
      <webElementGuid>59d4edf1-eb87-4353-ba8e-6bc952095dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ffffedc4-a2fe-4afa-9fc7-c4589a6daaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-item-47</value>
      <webElementGuid>9a67e9bc-75dc-4431-b5fe-52959de3ba34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tab-id</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>90df6eec-7315-4c6b-b9f6-35b217be4f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee2df3a6-83eb-4158-81d7-24f58814296d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3352158-a3d2-4af0-9839-ccc812b6dd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$mdTabsCtrl.select(tab.getIndex())</value>
      <webElementGuid>a1458c49-fcee-4ed2-8912-c79ba19b9e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = true</value>
      <webElementGuid>cd9f8962-3079-45f3-a49c-a7019e86353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdTabsCtrl.hasFocus = false</value>
      <webElementGuid>688e0e8e-5084-455c-afa3-5c1501350333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'md-active':    tab.isActive(), 'md-focused':   tab.hasFocus(), 'md-disabled':  tab.scope.disabled }</value>
      <webElementGuid>1c61a844-2bc1-4162-bc98-211ccb6ce8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>tab.scope.disabled</value>
      <webElementGuid>50576d42-9db8-4205-bed4-5248b1b54139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-left</name>
      <type>Main</type>
      <value>$mdTabsCtrl.nextPage()</value>
      <webElementGuid>42e280df-9bf1-4709-8a0a-8cbc96ea9a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-swipe-right</name>
      <type>Main</type>
      <value>$mdTabsCtrl.previousPage()</value>
      <webElementGuid>18144658-16b6-4d5e-9d9a-680abd9a7777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-tabs-template</name>
      <type>Main</type>
      <value>::tab.label</value>
      <webElementGuid>31e537ec-0397-4dac-9149-3731f5ee2dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-scope</name>
      <type>Main</type>
      <value>::tab.parent</value>
      <webElementGuid>27a4657d-b641-445b-94c1-6648cab10631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-content-47</value>
      <webElementGuid>5d67423c-d1db-4b3b-88df-c9b65caac525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incoming</value>
      <webElementGuid>af6dedba-9b22-41bb-856a-db222a46ea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-item-47&quot;)</value>
      <webElementGuid>8e4c3ff7-fe6c-4191-ae7c-26e7ab793edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id='tab-item-47']</value>
      <webElementGuid>ef6d4976-f817-4876-8db9-826a40b7fa5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/md-tabs/md-tabs-wrapper/md-tabs-canvas/md-pagination-wrapper/md-tab-item</value>
      <webElementGuid>79f4973c-092e-4f8d-9767-b20235b47eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reversal Pickings'])[3]/following::md-tab-item[1]</value>
      <webElementGuid>e5859c86-d632-4478-94ff-d3266bebeede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reversal Pickings'])[2]/following::md-tab-item[1]</value>
      <webElementGuid>9630f6d3-f5bb-4776-8ffa-93d0d101e59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outgoing'])[2]/preceding::md-tab-item[1]</value>
      <webElementGuid>3ca814b6-bb3b-4dd0-9811-c0d81dbe9d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming'])[3]/preceding::md-tab-item[2]</value>
      <webElementGuid>23330eae-28cb-4dac-95a5-48f41ffd4ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-tab-item</value>
      <webElementGuid>40bcbb1a-6e52-4b9c-825b-5cd23738f348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//md-tab-item[@id = 'tab-item-47' and (text() = 'Incoming' or . = 'Incoming')]</value>
      <webElementGuid>8f527bdc-624e-42df-8213-d9ddf7b91ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
