<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Partners</name>
   <tag></tag>
   <elementGuidId>d3c92a9c-d05f-4cfe-ac65-41a1e1df04cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Partners > a.layout-align-space-between-center.layout-row.flex > p.ng-binding.flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-list-item[@id='Partners']/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9421edc9-fbbc-48d4-9619-345d1f86a4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding flex</value>
      <webElementGuid>c8378711-d798-4ed8-a438-ad36e931cc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partners</value>
      <webElementGuid>3eaacd7f-3fa8-4ba5-a207-6914703a0ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Partners&quot;)/a[@class=&quot;layout-align-space-between-center layout-row flex&quot;]/p[@class=&quot;ng-binding flex&quot;]</value>
      <webElementGuid>807345ff-9c82-49b8-aaf5-4437b9192393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-list-item[@id='Partners']/a/p</value>
      <webElementGuid>c6981f7e-60f7-445f-a53e-4790b9457978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::p[15]</value>
      <webElementGuid>06fd7fa9-af93-45a2-8024-606e27f60a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studio'])[1]/following::p[15]</value>
      <webElementGuid>081c463f-07e8-4630-8492-b269a9ecf9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/preceding::p[15]</value>
      <webElementGuid>17046d8d-7389-4178-8929-371b41516634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/preceding::p[15]</value>
      <webElementGuid>b4066b4c-00a3-4e31-b994-9e688d65a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Partners']/parent::*</value>
      <webElementGuid>390e5235-36dd-4fe9-b600-b2f88d6c3da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-list[3]/md-list-item[5]/a/p</value>
      <webElementGuid>1b93801f-02b8-479e-8615-53e57bb0871c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Partners' or . = 'Partners')]</value>
      <webElementGuid>8b615295-afe1-4eea-a8f3-75bf888b566e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
