<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>349ef745-1b35-469f-9f60-870aac59abc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.md-raised.md-primary.md-button.md-ink-ripple.flex-gt-sm.md-dark-theme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>251fbc58-82ff-4d10-89c2-580223a79966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-raised md-primary md-button md-ink-ripple flex-gt-sm md-dark-theme</value>
      <webElementGuid>6f787e30-26ee-44a6-87c1-869b7862e4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>68620f59-1ec6-4262-a30c-2618dd438a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>9a4bf7a3-9314-429f-887c-5a8f8234d7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content layout-align-gt-sm-center-start layout-align-start-center layout-column&quot;]/form[@class=&quot;block-card login-card ng-valid-email ng-valid-pattern ng-valid-maxlength ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/md-card[@class=&quot;_md md-dark-theme&quot;]/md-card-footer[1]/div[@class=&quot;block-footer layout-xs-column layout-sm-column layout-align-gt-sm-center-center layout-row&quot;]/button[@class=&quot;md-raised md-primary md-button md-ink-ripple flex-gt-sm md-dark-theme&quot;]</value>
      <webElementGuid>764ae523-5f95-45da-a4d7-ac4c0c958d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>a2eb5806-36a6-4d4e-9ad2-23a037e3ef90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/form/md-card/md-card-footer/div/button</value>
      <webElementGuid>dd46b97a-f06a-4696-b288-18b0b0d9e042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lock'])[1]/following::button[1]</value>
      <webElementGuid>33791804-70c4-4ed6-892d-16ae053b343f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person'])[1]/following::button[1]</value>
      <webElementGuid>01159da7-df14-4133-b003-f85a4d5f6ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password?'])[1]/preceding::button[1]</value>
      <webElementGuid>17843818-6bd7-400d-864f-6104f470eaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dafe3d7a-c257-429a-a0b1-78a3b3ec57a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>b3e66cfa-2565-486f-9a53-0840b0e8d992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
