<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Frozen</name>
   <tag></tag>
   <elementGuidId>918b26a6-5dd4-4999-841b-ff44c5bacaba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top']/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a01db608-b530-4cd4-ac83-c9610427b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>header.title</value>
      <webElementGuid>ea55392a-0167-45be-96d4-ae2260bdf6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>89361c17-41b3-411e-803d-79ac5f1e7e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Frozen</value>
      <webElementGuid>fd4c4baf-7f55-4f09-bc36-117d22d7a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;content-title ng-scope layout-align-start-center layout-row&quot;]/h2[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>dcfa45b7-1644-471e-b175-2e54f22b26b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/div[2]/h2</value>
      <webElementGuid>2ae93780-1ff3-456b-8db0-5475e643c7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspension'])[2]/following::h2[1]</value>
      <webElementGuid>cf57e750-4546-41f4-848d-1585158d3e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[2]/following::h2[1]</value>
      <webElementGuid>b0063a03-8972-491d-8d81-b165326902ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Frozen'])[1]/preceding::h2[1]</value>
      <webElementGuid>5bab9518-64c9-4e3a-8c95-af643498ab84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frozen Supplier'])[1]/preceding::h2[1]</value>
      <webElementGuid>0287f692-2788-4b3d-9515-6788134e7d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Frozen']/parent::*</value>
      <webElementGuid>65a7ecea-7718-4bd3-9165-11e703d866c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>90fcb4ef-6963-496f-bba4-070b27e5a0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Frozen' or . = 'Frozen')]</value>
      <webElementGuid>474550a2-bf34-4f60-82d6-ec93d3287c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
