<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Product Attributes</name>
   <tag></tag>
   <elementGuidId>3143d823-e927-485f-8e24-374c94e99fdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top']/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d1ff2597-6c29-4d73-a833-934821081d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>header.title</value>
      <webElementGuid>84121bbc-ddf2-4d46-b91f-bcac35148b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>722e9764-06c2-4649-b1b3-9e90d00d0190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Attributes</value>
      <webElementGuid>3c93ba84-a08d-4afc-bc2f-76a8b40671b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;content-title ng-scope layout-align-start-center layout-row&quot;]/h2[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>c82dde19-265a-4955-9193-b8624df3fad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/div[2]/h2</value>
      <webElementGuid>956ed233-9297-4a18-be45-3c3fd2032c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products Attribute'])[2]/following::h2[1]</value>
      <webElementGuid>a27a66c5-cd55-4ed4-ae32-21384202ce4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/following::h2[1]</value>
      <webElementGuid>d4284c2b-9a24-4d59-bb8f-eee3f2be1c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Attribute'])[1]/preceding::h2[1]</value>
      <webElementGuid>555f37d3-c3db-48e7-8ff0-668f76ff9036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::h2[2]</value>
      <webElementGuid>7a658295-c8b8-4bbb-b218-13c53a3125fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Attributes']/parent::*</value>
      <webElementGuid>c975712a-b29c-473c-bc4e-f8f797ce4081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>bc72acdd-c7c2-49ed-953b-0dedc9d20d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Product Attributes' or . = 'Product Attributes')]</value>
      <webElementGuid>4248855c-239a-4fb9-8961-d9ee96864952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
