<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Cancellation</name>
   <tag></tag>
   <elementGuidId>38ab584d-2b7c-4a89-a8e8-c76ec7f8466d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Cancellation > a.layout-align-space-between-center.layout-row.flex > p.ng-binding.flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-list-item[@id='Cancellation']/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2f4c698a-c021-471c-a5dc-802f4fc65956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding flex</value>
      <webElementGuid>dd8b3fbd-6cee-4299-a775-bf1ecee85e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancellation</value>
      <webElementGuid>556e09dc-15fd-411b-a6b2-edb33b578199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cancellation&quot;)/a[@class=&quot;layout-align-space-between-center layout-row flex&quot;]/p[@class=&quot;ng-binding flex&quot;]</value>
      <webElementGuid>8cfd5ccd-6c87-40b7-b1c4-460707e87ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-list-item[@id='Cancellation']/a/p</value>
      <webElementGuid>340135e0-9e93-468d-afe0-210e2b870d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::p[11]</value>
      <webElementGuid>ac374c26-da75-488b-8e55-16dabf215c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studio'])[1]/following::p[11]</value>
      <webElementGuid>312e72de-1d1f-47db-917b-d991e4acc8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/preceding::p[36]</value>
      <webElementGuid>bcddcac5-1fd9-4af9-b83a-a64567fa1997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/preceding::p[36]</value>
      <webElementGuid>83bbbd3a-387a-4c50-9860-42d1a4d70b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancellation']/parent::*</value>
      <webElementGuid>63650417-5f92-4f9e-8c39-2a41aacff3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-list[3]/md-list-item[3]/a/p</value>
      <webElementGuid>73c63c10-4cf7-4f60-bd43-f5c0e188bc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Cancellation' or . = 'Cancellation')]</value>
      <webElementGuid>ac26b762-a7f3-473f-8fad-ec86197dbfc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
