<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sourcing</name>
   <tag></tag>
   <elementGuidId>38fbedfd-b9df-45bc-8ce7-6f0523f6d0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Sourcing > a.layout-align-space-between-center.layout-row.flex > p.ng-binding.flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-list-item[@id='Sourcing']/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45ba16e8-97a0-466a-8b31-38e8f6b11006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding flex</value>
      <webElementGuid>49e359e3-c1db-4436-9613-06e16edf7d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sourcing</value>
      <webElementGuid>3b11f44a-7073-4980-a180-0d14652deb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sourcing&quot;)/a[@class=&quot;layout-align-space-between-center layout-row flex&quot;]/p[@class=&quot;ng-binding flex&quot;]</value>
      <webElementGuid>08879100-d7e0-4473-901e-6fd00732aaab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-list-item[@id='Sourcing']/a/p</value>
      <webElementGuid>79809e50-d217-481e-b925-31373d558992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::p[5]</value>
      <webElementGuid>bbde9851-e0fb-4590-96a6-3bc410634547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studio'])[1]/following::p[5]</value>
      <webElementGuid>ea4ee699-eb07-4e43-b0e0-095a3d67b566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/preceding::p[42]</value>
      <webElementGuid>9886770b-d7a4-44c7-9b23-a27bdf81f880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/preceding::p[42]</value>
      <webElementGuid>ef376483-7d69-4a18-84b7-0bde02b711e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sourcing']/parent::*</value>
      <webElementGuid>053bab56-5b2b-4ed3-a750-334e04ebbd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-list-item[2]/a/p</value>
      <webElementGuid>8a521a3b-ced7-47b3-a01e-03032c8f210f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sourcing' or . = 'Sourcing')]</value>
      <webElementGuid>eaa66b56-014e-498b-a258-82baadf84a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
