<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>b7fc2570-8855-4771-b29f-9db4ec58db38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.md-raised.md-primary.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[30]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fb348b3-f7c6-4398-a1f1-1855396b41e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-raised md-primary md-button md-ink-ripple</value>
      <webElementGuid>a15aab45-15f2-4926-8312-5404cbfb7060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16294b98-7264-42cf-a46c-9c457b159764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.gridDataSource.read()</value>
      <webElementGuid>0b06b62d-1057-4418-9d9c-2120122eaff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Search
                    </value>
      <webElementGuid>188e167b-4ac6-47f0-90bb-c1a020e432f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/md-card[@class=&quot;az-data-grid ng-scope _md flex-100&quot;]/md-toolbar[@class=&quot;md-table-toolbar md-default ng-scope _md _md-toolbar-transitions&quot;]/div[@class=&quot;md-toolbar-tools az-toolbar-search&quot;]/form[@class=&quot;form-card ng-pristine ng-valid layout-row flex&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;layout-align-start-center layout-row&quot;]/button[@class=&quot;md-raised md-primary md-button md-ink-ripple&quot;]</value>
      <webElementGuid>c4843c9e-2a69-4ad2-90ff-5ce671d38ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[30]</value>
      <webElementGuid>e79c8037-f5e2-4266-9874-543ae5898801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/md-card/md-toolbar[3]/div/form/div/div[2]/button</value>
      <webElementGuid>351fbfa6-a87c-45ed-9c7d-0725db51a63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='InternalCode'])[1]/following::button[1]</value>
      <webElementGuid>f8ff84e5-6310-4d93-8ad3-68a0f237810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::button[1]</value>
      <webElementGuid>c178574c-227e-430c-bf68-b75e3dc5088f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::button[1]</value>
      <webElementGuid>fd55e7f8-d7ef-4d7a-8b39-40a766f84227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image'])[1]/preceding::button[3]</value>
      <webElementGuid>6aaf30b5-cd42-4237-ab76-374ac6c678bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>3746e3c1-d3a6-4ef8-a7c1-d7d89d27a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button</value>
      <webElementGuid>a55d3fb9-eb6f-4503-9dab-01d7eb1e0cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                        Search
                    ' or . = '
                        Search
                    ')]</value>
      <webElementGuid>607227da-2ba0-47b8-a3bf-a630b384f1ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
