<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Help</name>
   <tag></tag>
   <elementGuidId>4877cc62-c54e-48f9-9fe9-e18774d4e217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.md-raised.md-accent.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[28]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>660282e2-e15b-42c9-aeeb-a50086fdeb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-raised md-accent md-button md-ink-ripple</value>
      <webElementGuid>faa15b03-108b-433a-90a2-9becbd8451e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa1b9586-f382-4dc2-bf6d-10f38020d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>busy</value>
      <webElementGuid>b9b96438-db83-401c-a3c9-212be42b3052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.showSalesHelp($event,1,type)</value>
      <webElementGuid>8fccf8a3-ec03-4e7a-bf40-ab109d5031ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Help
        </value>
      <webElementGuid>8bbb1f26-280b-4825-9057-ee3e9c40ffb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[@class=&quot;layout-align-end-center layout-row&quot;]/sales-tutorial[@class=&quot;ng-isolate-scope&quot;]/button[@class=&quot;md-raised md-accent md-button md-ink-ripple&quot;]</value>
      <webElementGuid>b90ae6f0-4d40-4af4-9ffe-5c38341daf53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[28]</value>
      <webElementGuid>5006cf8a-d1da-4df4-aa32-cad69f66dc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div/sales-tutorial/button</value>
      <webElementGuid>d16c66c8-23c3-4f99-9eff-b7cfd9cd9f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Product'])[1]/following::button[1]</value>
      <webElementGuid>3094342a-229b-49a7-a572-fabafd7ca00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export All'])[1]/following::button[2]</value>
      <webElementGuid>56b001fb-cf89-4b45-89ba-4118d0708245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[2]</value>
      <webElementGuid>7b99c65c-d22b-4201-b221-6776aa7ba8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::button[2]</value>
      <webElementGuid>aa88b3b3-e366-4ebc-9e6c-9c049deb831e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help']/parent::*</value>
      <webElementGuid>27555b45-0038-41f4-b370-504161b24287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sales-tutorial/button</value>
      <webElementGuid>6da6786a-d471-40d2-9e3e-3679fbba9d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
        Help
        ' or . = '
        Help
        ')]</value>
      <webElementGuid>2b429682-d1a8-41f8-84d8-88a837837b02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
