<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Staff Order</name>
   <tag></tag>
   <elementGuidId>0bfa922e-a5d4-42ea-a873-50074d14fe5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top']/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8002d888-343e-43d6-bd2c-deaf5e84446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>header.title</value>
      <webElementGuid>9007a36b-842a-44a9-85fb-e2af279f2175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>ef9f2f28-6624-4434-a4f8-67b8e731dfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Order</value>
      <webElementGuid>e62fcdbe-7369-42bc-8407-dc29fff69f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;content-title ng-scope layout-align-start-center layout-row&quot;]/h2[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>8cf03a7d-4a06-40c8-aa83-462506c03cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/div[2]/h2</value>
      <webElementGuid>be2ad76e-d927-46ea-a02c-6b2e8590f107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Orders'])[2]/following::h2[1]</value>
      <webElementGuid>625aa5db-8fd3-47ed-9465-ba3fe2d2275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[3]/following::h2[1]</value>
      <webElementGuid>00771fe3-733f-41e9-a646-31074b617dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::h2[1]</value>
      <webElementGuid>e37e05d2-f5d6-40eb-937d-5a95331053bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting Payment'])[1]/preceding::h2[1]</value>
      <webElementGuid>630542b9-3b29-47eb-a2a6-de2ce84554e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Staff Order']/parent::*</value>
      <webElementGuid>11e24ddc-8c4f-47c8-8027-dd43cfb30963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>90e9a04b-e379-4160-b4e8-fd4b401b931b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Staff Order' or . = 'Staff Order')]</value>
      <webElementGuid>9fd1f6db-f5d4-4786-83bd-1a594a043149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
