<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Payment Amount</name>
   <tag></tag>
   <elementGuidId>0731e1d3-d2e4-4910-aa1d-aa354d22dcdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/md-card/div/div/table/thead/tr/th[9]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43c6ffcd-a925-46f2-ab53-98bfd70052c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>$column.title</value>
      <webElementGuid>23567c40-459c-4ba4-bfb9-a7964e6c8b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'sort-indicator': params.settings().sortingIndicator=='span'}</value>
      <webElementGuid>93a8090f-2205-4c88-a1ab-a461b6d0d0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>f962f0df-8069-43d6-8791-5304a361e537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Amount</value>
      <webElementGuid>7b986ef1-63f6-4cf6-93a6-463d6583bdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/md-card[@class=&quot;list-card _md&quot;]/div[@class=&quot;az-grid ng-scope flex-100&quot;]/div[@class=&quot;table-responsive-vertical&quot;]/table[@class=&quot;table table-hover table-striped&quot;]/thead[@class=&quot;ng-scope&quot;]/tr[@class=&quot;md-data-grid-sort-header ng-scope&quot;]/th[@class=&quot;data-grid-header&quot;]/div[@class=&quot;md-data-grid-header ng-scope&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>4bd7ecb1-9d83-41bc-92e4-7002272997b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/md-card/div/div/table/thead/tr/th[9]/div/span</value>
      <webElementGuid>84bfeef7-54d4-4471-8d43-a2b7e575f791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GST'])[1]/following::span[1]</value>
      <webElementGuid>b62fe57c-268d-4536-8002-ab7ac50d2aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Total before Tax'])[1]/following::span[2]</value>
      <webElementGuid>8dc83b04-1beb-4e9f-828f-0cfd7ebebe92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/preceding::span[1]</value>
      <webElementGuid>d31492f8-3b17-4478-a18a-bdd1ecf9180e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>1f269bb8-65b9-413c-a493-1fc6b4b60550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Amount']/parent::*</value>
      <webElementGuid>1a53aa9e-1c6d-44fb-8c9b-9fb76d66003c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[9]/div/span</value>
      <webElementGuid>a6ba74e2-6d30-4a56-a237-a508076d15b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Payment Amount' or . = 'Payment Amount')]</value>
      <webElementGuid>681986bb-318e-42f8-8c2b-87f326737425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
