<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Rewards Transaction</name>
   <tag></tag>
   <elementGuidId>45416f0d-103e-423a-8bc8-678edc1ffb4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.md-warn.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d31e237-fd11-477e-b2df-70e3ce654809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button md-ink-ripple</value>
      <webElementGuid>a93363d2-1d64-4818-be48-9d87f5346a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/FBRewards/FBCreditsTransaction/Create</value>
      <webElementGuid>15e610a6-a056-490f-a346-a7ee2b99a2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Rewards Transaction </value>
      <webElementGuid>7c92fbfe-f6f1-481b-8a4b-d10ca316cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;ng-scope layout-align-end-center layout-row&quot;]/a[@class=&quot;md-warn md-button md-ink-ripple&quot;]</value>
      <webElementGuid>578fbbde-dbb9-480c-986e-194ff8138c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/a</value>
      <webElementGuid>cc6d8058-a416-469a-8ae5-d0c448223048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Rewards Transaction')]</value>
      <webElementGuid>f778c688-b445-4f87-bea2-f83740187dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enquiry of Members Rewards Transaction List'])[1]/following::a[1]</value>
      <webElementGuid>36e9f887-738e-473a-bdb3-57c00b171024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rewards Transaction'])[2]/following::a[1]</value>
      <webElementGuid>025244ff-a717-4f12-91c1-ab0e8f022228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::a[1]</value>
      <webElementGuid>2bca80a0-3725-47eb-a4a4-a9eedb1f20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redeemed'])[1]/preceding::a[1]</value>
      <webElementGuid>6f162e9a-e800-4713-81c1-cdd3a03344e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Rewards Transaction']/parent::*</value>
      <webElementGuid>1a76ffe4-0133-41b7-b5a5-e79044b25d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/FBRewards/FBCreditsTransaction/Create')]</value>
      <webElementGuid>556e5b45-7dea-4721-a7dc-7e9baf167c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>a8a97112-1d0a-425d-90c8-6522bfcdbc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/FBRewards/FBCreditsTransaction/Create' and (text() = 'Add Rewards Transaction ' or . = 'Add Rewards Transaction ')]</value>
      <webElementGuid>6a498274-b0dc-4e8d-bffa-75ed2ed1506f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
