<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Points Rule Template</name>
   <tag></tag>
   <elementGuidId>32caca1e-bb6a-4c54-926f-394a80c57d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.md-warn.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b26f582-9de6-415a-b93c-ddca4a2160f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button md-ink-ripple</value>
      <webElementGuid>c82173a4-cd65-4036-bf1d-0b27442c5d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>FBRewards/PointsRule/Reward/template/Edit</value>
      <webElementGuid>beabd69c-f573-427a-a400-1ca30ac05f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Points Rule Template </value>
      <webElementGuid>299f6bcf-dd37-4bd4-858e-f45dc540d4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[@class=&quot;layout-align-end-center layout-row&quot;]/a[@class=&quot;md-warn md-button md-ink-ripple&quot;]</value>
      <webElementGuid>2b3d674e-c691-48aa-96ad-8f31e4f38c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div/a</value>
      <webElementGuid>473401f2-682d-467c-9c36-35cf78ff3e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Points Rule Template')]</value>
      <webElementGuid>9e7320e3-6990-4904-9162-783e2ab55fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Points Rule Template'])[1]/following::a[1]</value>
      <webElementGuid>82d9019b-885c-4c31-bd49-581d5ffef3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template'])[2]/following::a[1]</value>
      <webElementGuid>af91bb4f-4fdf-43b1-806b-f776a28fc5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::a[1]</value>
      <webElementGuid>3496a4c6-4423-4b3c-a673-e9772893ddd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Type'])[1]/preceding::a[1]</value>
      <webElementGuid>3551dabe-7366-43d0-b7f3-a05ca58d5594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Points Rule Template']/parent::*</value>
      <webElementGuid>b68a6cb7-d146-4b98-8b35-8e9a659f8e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'FBRewards/PointsRule/Reward/template/Edit')]</value>
      <webElementGuid>32530267-93cf-401e-a9e6-5c8de01b2c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>39ba8034-c736-4966-a0b9-3a1c88418a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'FBRewards/PointsRule/Reward/template/Edit' and (text() = 'Add Points Rule Template ' or . = 'Add Points Rule Template ')]</value>
      <webElementGuid>f0fd8c3f-b0dc-4d5b-8bf2-7b93f1bfa7f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
