<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Shopping Rebate</name>
   <tag></tag>
   <elementGuidId>0319c94b-bed9-4955-ade5-cbc7a79f20f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>21838198-ce08-4948-846a-31f03d44a846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>header.title</value>
      <webElementGuid>28698124-8e48-4460-ad56-119989feab46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2179dc95-90f7-46ec-889e-eda04cea132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shopping Rebate</value>
      <webElementGuid>a076e6a7-cfdd-456c-80f3-6ac4da1ae2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;content-title ng-scope layout-align-start-center layout-row&quot;]/h2[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>4d5518ff-68cd-4d52-81a8-20f3ac044496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/div/h2</value>
      <webElementGuid>7ecdc8fa-527e-4aaf-b0f1-9f9dbb06f032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/following::h2[1]</value>
      <webElementGuid>d7cb232b-f470-4d9d-abc3-596320a9ef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/following::h2[1]</value>
      <webElementGuid>d451e419-db95-4a3d-b107-20b734cfa87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::h2[1]</value>
      <webElementGuid>2baabbed-428f-429d-95e2-74d2fffdda5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::h2[1]</value>
      <webElementGuid>1003ae0b-1eeb-4ecd-9bb4-e38bbf065f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>bc91086b-922f-42e6-933d-46265b958199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Shopping Rebate' or . = 'Shopping Rebate')]</value>
      <webElementGuid>261ed0e0-9f2a-4006-9725-b4f0844e0f37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
