<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Budget Maintenance</name>
   <tag></tag>
   <elementGuidId>ea65a5dd-51a8-4d54-b821-ce5f4e99550b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.md-warn.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div/form/md-card/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07e31a49-7342-4569-8738-1d47b11fd68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button md-ink-ripple</value>
      <webElementGuid>6588ce56-385e-46d9-a722-9bbe4cd19c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Accounting/Journal/BudgetCost/BudgetCreate</value>
      <webElementGuid>8f184dea-0da0-4fcb-a84f-a4a4e1d30b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Budget Maintenance</value>
      <webElementGuid>d0f8ca59-117d-4982-8e35-fc2b538c922c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/form[@class=&quot;form-card ng-pristine ng-valid&quot;]/md-card[@class=&quot;_md&quot;]/div[@class=&quot;operation-toolbar operation-nav layout-align-start-center layout-row&quot;]/a[@class=&quot;md-warn md-button md-ink-ripple&quot;]</value>
      <webElementGuid>6f2b4708-1660-47d3-b965-653844dedd1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div/form/md-card/div[2]/a</value>
      <webElementGuid>746a6b49-971a-4bab-a05e-e7cae81d7a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Budget Maintenance')]</value>
      <webElementGuid>f270969f-0321-4bc1-9d80-8a8581f01c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Budget List'])[1]/following::a[1]</value>
      <webElementGuid>fbca24a3-51e5-45af-89f7-fd8d4f133dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/following::a[1]</value>
      <webElementGuid>e9fe911b-5d6a-4b49-9f9b-d4094dd56635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::a[1]</value>
      <webElementGuid>aa276852-7f51-49d1-bb6a-2677a5665bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::a[1]</value>
      <webElementGuid>c7b96b12-ede7-4ccc-aa65-567ab47ae443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Budget Maintenance']/parent::*</value>
      <webElementGuid>04286a32-db2f-476c-9c3e-5fcd37356e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Accounting/Journal/BudgetCost/BudgetCreate')]</value>
      <webElementGuid>8ba399fb-44c3-42c6-8117-60ba1879cac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-card/div[2]/a</value>
      <webElementGuid>af957501-90b2-4445-b60c-962f9a5e5bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Accounting/Journal/BudgetCost/BudgetCreate' and (text() = 'Budget Maintenance' or . = 'Budget Maintenance')]</value>
      <webElementGuid>1461f374-db1c-4669-a4b4-53c9d32bec02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
