<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export_1</name>
   <tag></tag>
   <elementGuidId>c4970d68-53b6-4fd8-9bef-9e09d8f0573d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.md-warn.md-button.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '
                    Export
                ' or . = '
                    Export
                ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57731e07-4cb8-4f75-a503-deec02d92775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button md-ink-ripple</value>
      <webElementGuid>41af24ce-b09f-4cf9-93ed-06ceeea098e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>
</value>
      <webElementGuid>4015b571-243f-4e84-aa30-fb4e9dad152d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(!gridDataSource || gridDataSource._view.length &lt;= 0) || busy</value>
      <webElementGuid>ab239aae-b808-4941-872c-ab2fc6a0b8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>generateFile()</value>
      <webElementGuid>dabfa658-4102-4cf1-9b06-99aa72c36e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Export
                </value>
      <webElementGuid>d5899441-90c4-47fa-9afb-45dbac30c011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/form[@class=&quot;form-card ng-pristine ng-valid-md-multiple ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required&quot;]/md-card[@class=&quot;_md&quot;]/div[@class=&quot;list-search&quot;]/div[@class=&quot;layout-wrap layout-xs-column layout-sm-column layout-row&quot;]/button[@class=&quot;md-warn md-button md-ink-ripple&quot;]</value>
      <webElementGuid>b0f1ed35-0bbe-4f3b-aa24-46a9f68458de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>5db3c80d-bb4d-4cfa-9141-8f4ce4f7d2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div/form/md-card/div[2]/div[2]/button</value>
      <webElementGuid>f5c5d02c-b04a-4cb9-bb90-2a783d10c7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::button[1]</value>
      <webElementGuid>d7265ee2-15b0-43e9-95b4-49b94f38e63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPENING OF 2023'])[2]/following::button[1]</value>
      <webElementGuid>7d104659-eaf3-4608-ab4a-3b80565fbb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::button[1]</value>
      <webElementGuid>19b9301a-6704-45e1-8653-2dadf24ddabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::button[1]</value>
      <webElementGuid>9e664e75-2083-4c79-9103-c6dd86c5a4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export']/parent::*</value>
      <webElementGuid>934d7908-d898-443c-ae17-9a38b7e82adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>0a4b6944-ab34-4632-8e97-c781ba0490ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Export
                ' or . = '
                    Export
                ')]</value>
      <webElementGuid>31b02813-0e9e-43ed-9780-c1a9a61599ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
