<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Journals</name>
   <tag></tag>
   <elementGuidId>98f37b43-b9ac-484a-99cc-2f820bc164c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Journals > a.layout-align-space-between-center.layout-row.flex > p.ng-binding.flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-list-item[@id='Journals']/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6d351e6f-6e8e-4cd9-b5ea-b33173316e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding flex</value>
      <webElementGuid>77191b13-899f-4af9-a8bd-b1c95c45c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Journals</value>
      <webElementGuid>332ce2db-6a4e-451e-b656-9b733ade46b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Journals&quot;)/a[@class=&quot;layout-align-space-between-center layout-row flex&quot;]/p[@class=&quot;ng-binding flex&quot;]</value>
      <webElementGuid>18397a8f-3dfa-4c40-8d88-135a9c53874e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-list-item[@id='Journals']/a/p</value>
      <webElementGuid>c4e4ba8f-9825-46ae-8c24-13e30b9ae899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::p[15]</value>
      <webElementGuid>ce127adf-252e-414f-8fac-1b0350c2a517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studio'])[1]/following::p[15]</value>
      <webElementGuid>fe7393f8-2c18-4e9d-b8bf-8d49fb226c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/preceding::p[9]</value>
      <webElementGuid>2778cfe9-427b-4bd9-a8b9-7ae2ac2e8628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/preceding::p[9]</value>
      <webElementGuid>e7ec1216-8ec7-4524-84e0-e99cc2935161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Journals']/parent::*</value>
      <webElementGuid>fe41d7e2-f150-4917-b00c-5469ba440eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-list[4]/md-list-item[3]/a/p</value>
      <webElementGuid>0d57a08a-3368-4bfa-a77a-27708c6ecd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Journals' or . = 'Journals')]</value>
      <webElementGuid>5b2742d2-2cb1-490e-be1c-f9da3805544a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
