<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Batch Import</name>
   <tag></tag>
   <elementGuidId>49867f92-af6b-4557-9f8c-69d568a13e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9b39bf4-7ce7-4abe-984a-bf9ddf4275da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button ng-scope md-ink-ripple</value>
      <webElementGuid>7d1dc3c0-4a80-43c1-8ded-f00703a2035b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>MembershipAR/AR/Payment/ImportStep</value>
      <webElementGuid>bbcb7b50-b434-49f7-8667-eb49ac50c48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.ARuserRight.HasPaymentBatchImportRight</value>
      <webElementGuid>f03e6c08-4c07-453c-9c36-78c435f3b043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batch Import</value>
      <webElementGuid>2db1830b-1f26-48cb-86dd-722434df2042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[@class=&quot;layout-align-end-center layout-row&quot;]/a[@class=&quot;md-warn md-button ng-scope md-ink-ripple&quot;]</value>
      <webElementGuid>13db42fd-8aed-4923-a970-f0ee6465edd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div/a[3]</value>
      <webElementGuid>fd4569ae-c90b-4111-8575-054033360b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Batch Import')])[3]</value>
      <webElementGuid>09776f39-41a7-4da3-bf83-44b8cd0fb2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DBS Batch Import'])[1]/following::a[1]</value>
      <webElementGuid>3901321d-e12f-42b9-9d47-ead8862270fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheque Batch Import'])[1]/following::a[2]</value>
      <webElementGuid>8860beb7-2fba-46e0-912a-0b7cccda8cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Payment'])[1]/preceding::a[1]</value>
      <webElementGuid>26f135fd-eafc-45f9-8e6c-dbd7af268d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay for reminder'])[1]/preceding::a[2]</value>
      <webElementGuid>4342f17f-edce-4d0d-8d06-89d5021c28d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batch Import']/parent::*</value>
      <webElementGuid>17d2a8f5-6c7f-4a4d-b9e5-56945c33ead4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'MembershipAR/AR/Payment/ImportStep')]</value>
      <webElementGuid>333ce330-d1ea-4d39-9c47-61f4206a75bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[3]</value>
      <webElementGuid>21c8d669-8c34-428e-90a3-6e49f7024667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'MembershipAR/AR/Payment/ImportStep' and (text() = 'Batch Import' or . = 'Batch Import')]</value>
      <webElementGuid>965f589e-7e16-4990-af79-f947149e6b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
