<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cheque Batch Import</name>
   <tag></tag>
   <elementGuidId>60f920fc-3a87-4ddf-9562-ae0a8372e57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.md-warn.md-button.ng-scope.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'MembershipAR/AR/Payment/ChequeImportStep?tag=Cheque' and (text() = 'Cheque Batch Import' or . = 'Cheque Batch Import')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4bf0158-c2d7-452c-af75-d46b9079e049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button ng-scope md-ink-ripple</value>
      <webElementGuid>80edd85b-5bfa-4767-a7a5-32751c5668a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>MembershipAR/AR/Payment/ChequeImportStep?tag=Cheque</value>
      <webElementGuid>4f240cc5-f75e-4a49-91cd-ad34be439bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.ARuserRight.HasPaymentBatchImportRight</value>
      <webElementGuid>41886337-3099-46a4-82b8-33326a095758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cheque Batch Import</value>
      <webElementGuid>e2d3ea1c-ac3a-48da-aa0f-d73d4348ec28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[@class=&quot;layout-align-end-center layout-row&quot;]/a[@class=&quot;md-warn md-button ng-scope md-ink-ripple&quot;]</value>
      <webElementGuid>ad63eb33-71f6-4990-bfd1-dbb1c79668d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div/a</value>
      <webElementGuid>f030b89a-cff7-4e39-bf1e-f6aa7dec6144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cheque Batch Import')]</value>
      <webElementGuid>317b9026-589c-4e43-9eae-fc77dd5668dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment History List'])[1]/following::a[1]</value>
      <webElementGuid>88393ff2-ca90-4d85-93bf-d640df8eaa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membership'])[2]/following::a[1]</value>
      <webElementGuid>6d2c9d2e-2ebe-497c-a15e-96c0844b72e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DBS Batch Import'])[1]/preceding::a[1]</value>
      <webElementGuid>2b73eb6b-2169-44b2-acc2-ee9d4ba17506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Import'])[1]/preceding::a[2]</value>
      <webElementGuid>448fa878-f998-4816-a93c-dc9a007ab901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cheque Batch Import']/parent::*</value>
      <webElementGuid>29068fe3-cbdf-4183-ada3-d29c4b2b1696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'MembershipAR/AR/Payment/ChequeImportStep?tag=Cheque')]</value>
      <webElementGuid>b29d06e6-140e-46e9-82cb-3eea99e55cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>ca10c374-42d3-4056-a87a-8af6a0744325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'MembershipAR/AR/Payment/ChequeImportStep?tag=Cheque' and (text() = 'Cheque Batch Import' or . = 'Cheque Batch Import')]</value>
      <webElementGuid>0050c87e-51cd-41f9-bd94-41394b965414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
