<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rollback Payment</name>
   <tag></tag>
   <elementGuidId>a087cd26-8100-490c-af98-0d0d15a8796e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/div/a[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'MembershipAR/AR/Payment/PaymentRollbackList' and (text() = 'Rollback Payment' or . = 'Rollback Payment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9346bc6-0d13-4dac-9893-a7cda3c7f094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-warn md-button ng-scope md-ink-ripple</value>
      <webElementGuid>22ca1bb3-f73c-40e4-9657-5503fe751a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>MembershipAR/AR/Payment/PaymentRollbackList</value>
      <webElementGuid>9e3f5463-c4a3-4b08-9ea8-01de35863977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.ARuserRight.HasPaymentRollbackRight</value>
      <webElementGuid>8cbcb9f1-a312-46d3-83e0-e45365e09c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rollback Payment</value>
      <webElementGuid>d1cd669b-3d07-457a-af80-33fb44d7c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[@class=&quot;layout-align-end-center layout-row&quot;]/a[@class=&quot;md-warn md-button ng-scope md-ink-ripple&quot;]</value>
      <webElementGuid>8b7590fa-cb25-40ca-9654-2dede4112fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div/a[6]</value>
      <webElementGuid>985228da-2ff5-4431-9301-8e3e09d54b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rollback Payment')]</value>
      <webElementGuid>63fa5b73-a0a0-45f8-b7e4-bf10c83319c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay for reminder'])[1]/following::a[1]</value>
      <webElementGuid>2dcf2b03-da66-4366-9b7e-d84f7a372cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Payment'])[1]/following::a[2]</value>
      <webElementGuid>0afa6ebf-c691-425f-af45-bc1ef5bd6edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::a[1]</value>
      <webElementGuid>1e35a1ad-0d40-48dd-8f91-a247a98b5e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::a[1]</value>
      <webElementGuid>fc4a3fc4-c537-4689-9329-6bdc62ca23ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rollback Payment']/parent::*</value>
      <webElementGuid>3e9301f4-5f86-4f5e-83c6-b23aa63ec64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'MembershipAR/AR/Payment/PaymentRollbackList')]</value>
      <webElementGuid>9526ed17-666f-41b5-b4fb-448e53d85d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>7b13b210-d1c3-4426-ae6a-c87c9738655f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'MembershipAR/AR/Payment/PaymentRollbackList' and (text() = 'Rollback Payment' or . = 'Rollback Payment')]</value>
      <webElementGuid>40da00e4-7f4a-4306-819f-7e738d1d97e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
