<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Statements</name>
   <tag></tag>
   <elementGuidId>232c8926-fa28-4de0-8e55-edbaf9e7ebbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.collapse-toggle > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/div[2]/form/md-card/md-card-content[2]/h4/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb7aedbb-2e32-45f9-8fa1-d84ff0af0ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Statements</value>
      <webElementGuid>fac64337-36d7-4026-addc-e3988a7f3d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/div[2]/form[@class=&quot;form-card ng-pristine ng-invalid ng-invalid-required ng-valid-md-multiple&quot;]/md-card[@class=&quot;_md&quot;]/md-card-content[@class=&quot;collapse md-card-content-has-title&quot;]/h4[@class=&quot;collapse-toggle&quot;]/span[1]</value>
      <webElementGuid>fcf6e7d5-855e-4834-b7b2-387d6180bf95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/div[2]/form/md-card/md-card-content[2]/h4/span</value>
      <webElementGuid>e4bc93c2-cfc2-4e7b-bbe1-68640353d742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[1]</value>
      <webElementGuid>e74a5f10-51e9-47f0-862a-894d115e6066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/following::span[1]</value>
      <webElementGuid>65d2cb14-30c4-45c8-8fdf-5ed0265d5982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Id'])[2]/preceding::span[1]</value>
      <webElementGuid>cbe88a34-74e3-4fef-8b99-e3cc05f818f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Name'])[2]/preceding::span[2]</value>
      <webElementGuid>8d34ddff-31f2-4277-9848-41963f2679ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Statements']/parent::*</value>
      <webElementGuid>34a5c424-57e3-499e-b228-d25d4accb4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/span</value>
      <webElementGuid>7e7d4bb1-5c3e-417c-80c2-6461574f3b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Statements' or . = 'Statements')]</value>
      <webElementGuid>d27e61a2-18b2-4bcf-9033-8274e604526e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
