<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save as Draft</name>
   <tag></tag>
   <elementGuidId>db98a52a-9d0f-4f14-aceb-4c35c9343bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.md-raised.md-primary.md-button.ng-scope.md-ink-ripple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Save as Draft' or . = 'Save as Draft')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59a277f5-e31e-4ee0-a0bf-c2ac0921bf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-raised md-primary md-button ng-scope md-ink-ripple</value>
      <webElementGuid>906d311d-e1c3-4b39-90eb-e4ee86a878c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ae606d77-46bd-4435-9330-4d3dc197db68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.busy</value>
      <webElementGuid>e35b5af9-a724-4982-826d-dc49394ff81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!view</value>
      <webElementGuid>279d2fa5-5475-4cde-a244-34d63d7c7282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.save()</value>
      <webElementGuid>de02859c-6e7e-4f60-bed3-18a0621903b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save as Draft</value>
      <webElementGuid>57800bc4-0e96-4d8d-bdd1-87dd5fc770b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;content-main ng-scope&quot;]/div[@class=&quot;content-body ng-scope&quot;]/form[@class=&quot;form-card ng-pristine ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength ng-valid-mindate ng-valid-maxdate ng-valid-filtered ng-valid-valid&quot;]/md-card[@class=&quot;_md&quot;]/md-card-content[@class=&quot;md-card-content-no-title&quot;]/div[1]/button[@class=&quot;md-raised md-primary md-button ng-scope md-ink-ripple&quot;]</value>
      <webElementGuid>8894d89b-86d4-4038-b04c-18a9b4f95134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>95ec2290-95cf-47a0-92cc-50cbe07bd318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/form/md-card/md-card-content[2]/div/button</value>
      <webElementGuid>a4f59a87-61f1-4013-a1da-45387d83a6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::button[1]</value>
      <webElementGuid>51f7a066-4f84-460f-a5f3-6d156b3aa959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editorial Panel'])[1]/following::button[1]</value>
      <webElementGuid>8d01cc02-02ec-4faf-8527-3d9a02917049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[1]</value>
      <webElementGuid>3c2d8997-241b-48d5-ad6d-7d90e89b256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>fe766d09-72c7-4a40-85a7-c3879037e932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save as Draft']/parent::*</value>
      <webElementGuid>a1373eab-d18c-4cc9-92b8-3443b59b70dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-card-content[2]/div/button</value>
      <webElementGuid>10894a72-6c89-410b-887d-6834807a039e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Save as Draft' or . = 'Save as Draft')]</value>
      <webElementGuid>6abfb494-04f7-43ff-9fd0-23b8b2323057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
