<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Member Name_MemberName</name>
   <tag></tag>
   <elementGuidId>5306cb8d-8f34-429d-b1bf-d0cd324ef7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_49']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>606d039f-ad5f-4cec-b424-1783fba7377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68536b46-30de-4aac-ae08-a5094464085f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MemberName</value>
      <webElementGuid>85bcb089-d021-4808-b822-7b4878e051fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>vm.memberNameChange(Member.Member.Name)</value>
      <webElementGuid>ca940219-ef02-4a52-b59a-1e9f64f36393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>Member.Member.Name</value>
      <webElementGuid>6c6ecb77-830c-4314-bf6c-54c88ff4e53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-scope md-input ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>d71482ed-65d1-4c54-a360-45be7a1520d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_49</value>
      <webElementGuid>c4d8f508-e691-4b6b-b97d-c676ab6dfff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd8a83d6-a95a-4e45-a962-ffb1123ac79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d04e4b54-2cc3-4532-a9c3-28814ae89193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_49&quot;)</value>
      <webElementGuid>6577c1e0-5924-4c55-b5e7-5466fdb7cc54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_49']</value>
      <webElementGuid>abf2c556-b6cb-4b86-b31f-294ffc79aae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-input-container[@id='Membership_Members_Create_form1_MemberMemberName']/input</value>
      <webElementGuid>833e8213-c6a4-46e6-a7f8-e2d4345932f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-input-container[4]/input</value>
      <webElementGuid>ebad1b66-8573-4b86-ae97-839357619549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'MemberName' and @id = 'input_49']</value>
      <webElementGuid>cddba576-2e13-4e56-9a78-4f1544bef20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
