<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transaction</name>
   <tag></tag>
   <elementGuidId>14b1441b-412a-4f19-9b3a-e98af062c9fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section_2 > h4.collapse-toggle > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-card-content[@id='section_2']/h4/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Transaction' or . = 'Transaction')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d017e18-8a34-438e-b702-caedc3a4a4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction</value>
      <webElementGuid>fb2c7bcb-1080-43c4-af69-e1ad6604ea5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section_2&quot;)/h4[@class=&quot;collapse-toggle&quot;]/span[1]</value>
      <webElementGuid>62f58484-0afc-44ce-b5bf-0908eb2eaf35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-card-content[@id='section_2']/h4/span</value>
      <webElementGuid>b886f3d7-b5b5-4bce-8baf-8dd357cc3081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Balance'])[1]/following::span[1]</value>
      <webElementGuid>f33d342e-6409-4ee3-8e18-70e246ad4209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membership Type is required.'])[1]/following::span[1]</value>
      <webElementGuid>ab319aac-fc03-472d-89f1-03fcc9277e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription Fee Type'])[2]/preceding::span[1]</value>
      <webElementGuid>c6b19f56-04be-44e9-aebb-303e6612a869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBS FEE $40'])[1]/preceding::span[3]</value>
      <webElementGuid>3c15d8a1-67a4-49cd-a74e-7d803dca4ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transaction']/parent::*</value>
      <webElementGuid>f084c04d-1623-46a6-83db-e6a965b40729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-card-content[2]/h4/span</value>
      <webElementGuid>a879f57a-4e35-4fd2-bb12-54595fa06e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction' or . = 'Transaction')]</value>
      <webElementGuid>6e77bffe-217d-4f43-a998-60a17314978f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
