<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Requests</name>
   <tag></tag>
   <elementGuidId>cbcce68f-aaf5-4eb0-978c-ec7e9bffccf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section_3 > div.layout-wrap.layout-xs-column.layout-sm-column.layout-row > div.layout-wrap.layout-xs-column.layout-sm-column.layout-align-gt-sm-start-start.layout-row.flex-100 > div.layout-column > md-grid-list.dashboard-grid.ng-isolate-scope._md > md-grid-tile.dashboard-tile.md-clickable.ng-isolate-scope > figure > a.ng-scope.flex > div.card-tile.layout-align-space-between-center.layout-row.flex > div.card-tile-text.layout-align-center-start.layout-column > span:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-card-content[@id='section_3']/div/div/div/md-grid-list/md-grid-tile/figure/a/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ac5dd5e-a206-4def-86e1-48a3bba023e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Requests</value>
      <webElementGuid>fff546e0-253a-40e4-9f42-e9090690f3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section_3&quot;)/div[@class=&quot;layout-wrap layout-xs-column layout-sm-column layout-row&quot;]/div[@class=&quot;layout-wrap layout-xs-column layout-sm-column layout-align-gt-sm-start-start layout-row flex-100&quot;]/div[@class=&quot;layout-column&quot;]/md-grid-list[@class=&quot;dashboard-grid ng-isolate-scope _md&quot;]/md-grid-tile[@class=&quot;dashboard-tile md-clickable ng-isolate-scope&quot;]/figure[1]/a[@class=&quot;ng-scope flex&quot;]/div[@class=&quot;card-tile layout-align-space-between-center layout-row flex&quot;]/div[@class=&quot;card-tile-text layout-align-center-start layout-column&quot;]/span[2]</value>
      <webElementGuid>51298684-c8ca-442a-bba9-90a2799b8479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-card-content[@id='section_3']/div/div/div/md-grid-list/md-grid-tile/figure/a/div/div/span[2]</value>
      <webElementGuid>cb2b9fc5-e6e8-4535-b7e1-24b0f5ff94d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Tasks'])[2]/following::span[2]</value>
      <webElementGuid>4c7233a0-f83b-496a-a497-8d664d6fa1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/following::span[4]</value>
      <webElementGuid>44f521a2-c0fc-4fb2-b716-146d49a259e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participation'])[1]/preceding::span[2]</value>
      <webElementGuid>622540d7-320d-4e1d-84ca-eabc67ea25ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delegations'])[1]/preceding::span[4]</value>
      <webElementGuid>6f60ba67-27b9-4fe3-a896-d45c48f38b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-card-content[4]/div/div/div/md-grid-list/md-grid-tile/figure/a/div/div/span[2]</value>
      <webElementGuid>70727997-b00b-4ce2-9459-1259781dee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Requests' or . = 'Requests')]</value>
      <webElementGuid>09cf6928-7e47-4b7b-9bf0-a1d9ff533813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
